### ISSUE TITLE
Enhancement - Suggestion

### ISSUE THREAD

**Issue by spsf64** [dolphinoracle/mx-sound-theme-borealis#1]
There are some missing events/sounds missing, I think these will enhance the user experience, please add:

menu-click.ogg
menu-popup.ogg
message.ogg
window-attention.ogg

These will only work with Compiz but are also great:
window-shade-down.ogg
window-shade-up.ogg
window-slide.ogg

Thank you for the great MX project and your youtube videos!

**Comment by dolphinoracle** [comment]
I've just uploaded to my github a new package for mx-sound-theme-borealis with what I hope are new events:

menu-click.ogg
menu-popup.ogg
message.ogg
window-attention.ogg

I'm not one for sound editing, so I included symlinks to existing files inside the theme.  In my limited testing they seem to work.  

This has not been sent up to the mx repo as yet, so if you see any problem, please let me know.
and thanks!  

d.o.
